import { EffectField } from '../../types/formFieldTypes';

export const effectFields: EffectField[] = [
    { name: "Test Time", key: "test_time", type: "option", desc: "Time of the testing", options: ["baseline(pre-test)", "post-test", "follow-up"], database_name:"time" },
    { name: "Gender 1 (Males)", key: "gender_1", type: "number", desc: "Number of males included in the study" },
    { name: "Gender 2 (Females)", key: "gender_2", type: "number", desc: "Number of females included in the study" },
    { name: "Gender 3 (Other)", key: "gender_3", type: "number", desc: "Number of other genders included in the study" },
    { name: "Effect Size Type", key: "effect_size_type", type: "option", desc: "Type of effect size", options: ["SMD", "RR/OR"], database_name:"name" },
    { name: "Age mean (Experimental Group)", key: "mean_age_1i", type: "number", desc: "Mean age of participants in the experimental group" },
    { name: "Mean of experimental group", key: "m1i", type: "number", desc: "Mean score of the experimental group" },
    { name: "Standard deviation of experimental group", key: "sd1i", type: "number", desc: "Standard deviation of the experimental group" },
    { name: "Number of participants in experimental group", key: "n1i", type: "number", desc: "Number of participants in the experimental group" },
    { name: "Age mean (Control Group)", key: "mean_age_2i", type: "number", desc: "Mean age of participants in the control group" },
    { name: "Mean of control group", key: "m2i", type: "number", desc: "Mean score of the control group" },
    { name: "Standard deviation in control group", key: "sd2i", type: "number", desc: "Standard deviation of the control group" },
    { name: "Number of participants in control group", key: "n2i", type: "number", desc: "Number of participants in the control group" },
    { name: "Intracluster correlation coefficient", key: "icc", type: "number", desc: "Intracluster correlation coefficient" },
    { name: "Events in group a", key: "ai", type: "number", desc: "Number of events in group a" },
    { name: "Events in group b", key: "bi", type: "number", desc: "Number of events in group b" },
    { name: "Events in group c", key: "ci", type: "number", desc: "Number of events in group c" },
    { name: "Events in group d", key: "di", type: "number", desc: "Number of events in group d" },
    { name: "Pearson's correlation", key: "ri", type: "number", desc: "Pearson's correlation coefficient" },
    { name: "T-test", key: "t", type: "number", desc: "T-test statistics" },
    { name: "F-statistics", key: "f_stat", type: "number", desc: "F-statistics" },
    { name: "Cohen's D", key: "d", type: "number", desc: "Cohen's D effect size" },
    { name: "Cohen's D variance", key: "d_var", type: "number", desc: "Variance of Cohen's D effect size" },
    { name: "Outcome", key: "outcome", type: "string", desc: "Machine-readable outcome (e.g., phon_aware)" },
    { name: "Test Name", key: "test_name", type: "string", desc: "Name of the test used" },
    { name: "Full outcome Name", key: "outcome_full", type: "string", desc: "Full name of the outcome as stated in the study (e.g., Phonological awareness)" },
    { name: "Outcome Operationalization", key: "outcome_op", type: "multiline", desc: "Description of how the outcome was measured", width: "93%" },
];
